# Generated by Django 3.0.8 on 2020-07-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20200728_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='note',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
