# Generated by Django 3.0.8 on 2020-07-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_userdetails_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='note',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='note',
            field=models.ManyToManyField(blank=True, related_name='_userdetails_note_+', to='test_app.UserDetails'),
        ),
    ]
