# Generated by Django 3.0.8 on 2020-07-28 05:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20200728_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='note',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=6000, null=True, size=50),
        ),
    ]
